"""Add apikey table

Revision ID: a_new_unique_id
Revises: some_unique_id  # This should be the revision ID from the PREVIOUS migration file
Create Date: 2025-09-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0002_add_api_keys'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
